version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: admin-app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        ports:
            - "8003:8000"
        networks:
            - kamlinko-network # ✅ ganti network
        environment:
            - DB_HOST=be-mysql # ✅ gunakan nama container MySQL
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    nginx:
        image: nginx:latest
        container_name: admin-nginx
        ports:
            - "8004:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - kamlinko-network # ✅ ganti network

    admin-vite:
        build:
            context: .
            dockerfile: Dockerfile.vite
        container_name: admin-vite
        ports:
            - "5174:5174"
        volumes:
            - .:/var/www/html
            - /etc/letsencrypt:/etc/letsencrypt:ro
        networks:
            - kamlinko-network # ✅ ganti network

networks:
    kamlinko-network: # ✅ gunakan network bersama
        external: true

volumes:
    mysql_data:
